import type {
  Venue,
  PR,
  Reservation,
  Event,
  Guest,
  Conversation,
  Message,
} from '@/types'

// ─── Venues ────────────────────────────────────────────────────────────────────

export const venues: Venue[] = [
  {
    id: 'venue-1',
    name: 'L\'Arc Casablanca',
    type: 'club',
    city: 'Casablanca',
    address: '12 Boulevard de la Corniche, Casablanca',
    capacity: 800,
    description: 'Iconic Casablanca nightclub on the Corniche, blending fine dining with world-class clubbing.',
    openingHours: '23:00 - 06:00',
    coverImage: '/venues/larc.jpg',
    tables: [
      { id: 't-1-1', number: 1, type: 'vip', capacity: 10, minimumSpend: 5000, shape: 'round', position: { x: 10, y: 15 }, status: 'reserved' },
      { id: 't-1-2', number: 2, type: 'vip', capacity: 8, minimumSpend: 3000, shape: 'rectangle', position: { x: 25, y: 15 }, status: 'available' },
      { id: 't-1-3', number: 3, type: 'standard', capacity: 6, minimumSpend: 1500, shape: 'round', position: { x: 40, y: 30 }, status: 'occupied' },
      { id: 't-1-4', number: 4, type: 'standard', capacity: 6, minimumSpend: 1500, shape: 'round', position: { x: 55, y: 30 }, status: 'available' },
      { id: 't-1-5', number: 5, type: 'bar', capacity: 4, minimumSpend: 800, shape: 'rectangle', position: { x: 70, y: 50 }, status: 'available' },
      { id: 't-1-6', number: 6, type: 'vip', capacity: 12, minimumSpend: 8000, shape: 'rectangle', position: { x: 10, y: 50 }, status: 'blocked' },
    ],
  },
  {
    id: 'venue-2',
    name: 'Jimmy\'z Marrakech',
    type: 'club',
    city: 'Marrakech',
    address: 'Avenue Mohamed VI, Hivernage, 40000 Marrakech',
    capacity: 500,
    description: 'Legendary Marrakech nightclub, the playground of the jet-set in the Red City.',
    openingHours: '23:30 - 05:00',
    coverImage: '/venues/jimmyz.jpg',
    tables: [
      { id: 't-2-1', number: 1, type: 'vip', capacity: 10, minimumSpend: 10000, shape: 'round', position: { x: 15, y: 20 }, status: 'reserved' },
      { id: 't-2-2', number: 2, type: 'vip', capacity: 8, minimumSpend: 6000, shape: 'round', position: { x: 35, y: 20 }, status: 'available' },
      { id: 't-2-3', number: 3, type: 'standard', capacity: 6, minimumSpend: 3000, shape: 'rectangle', position: { x: 55, y: 35 }, status: 'occupied' },
      { id: 't-2-4', number: 4, type: 'bar', capacity: 4, minimumSpend: 1500, shape: 'rectangle', position: { x: 75, y: 50 }, status: 'available' },
    ],
  },
  {
    id: 'venue-3',
    name: 'Baoli Tanger',
    type: 'lounge',
    city: 'Tanger',
    address: 'Avenue Mohammed VI, Zone Touristique, 90000 Tanger',
    capacity: 350,
    description: 'Asian-fusion restaurant and lounge on the waterfront, a staple of Tanger nightlife.',
    openingHours: '20:00 - 04:00',
    coverImage: '/venues/baoli.jpg',
    tables: [
      { id: 't-3-1', number: 1, type: 'vip', capacity: 8, minimumSpend: 4000, shape: 'rectangle', position: { x: 10, y: 10 }, status: 'available' },
      { id: 't-3-2', number: 2, type: 'standard', capacity: 6, minimumSpend: 1500, shape: 'round', position: { x: 30, y: 25 }, status: 'reserved' },
      { id: 't-3-3', number: 3, type: 'standard', capacity: 4, minimumSpend: 1000, shape: 'round', position: { x: 50, y: 25 }, status: 'available' },
      { id: 't-3-4', number: 4, type: 'bar', capacity: 4, minimumSpend: 500, shape: 'rectangle', position: { x: 70, y: 40 }, status: 'occupied' },
      { id: 't-3-5', number: 5, type: 'vip', capacity: 10, minimumSpend: 6000, shape: 'rectangle', position: { x: 10, y: 45 }, status: 'available' },
    ],
  },
  {
    id: 'venue-4',
    name: 'Le Comptoir de la Sqala',
    type: 'restaurant',
    city: 'Casablanca',
    address: '8 Boulevard des Almohades, Casablanca',
    capacity: 120,
    description: 'Chic Casablanca restaurant with late-night dining and a curated cocktail program.',
    openingHours: '19:00 - 02:00',
    coverImage: '/venues/comptoir.jpg',
    tables: [
      { id: 't-4-1', number: 1, type: 'vip', capacity: 6, minimumSpend: 500, shape: 'round', position: { x: 15, y: 15 }, status: 'available' },
      { id: 't-4-2', number: 2, type: 'standard', capacity: 4, minimumSpend: 200, shape: 'rectangle', position: { x: 35, y: 15 }, status: 'reserved' },
      { id: 't-4-3', number: 3, type: 'standard', capacity: 4, minimumSpend: 200, shape: 'rectangle', position: { x: 55, y: 15 }, status: 'available' },
      { id: 't-4-4', number: 4, type: 'standard', capacity: 2, minimumSpend: 100, shape: 'round', position: { x: 75, y: 30 }, status: 'occupied' },
      { id: 't-4-5', number: 5, type: 'bar', capacity: 4, minimumSpend: 150, shape: 'rectangle', position: { x: 50, y: 45 }, status: 'available' },
    ],
  },
  {
    id: 'venue-5',
    name: 'Twiga Marrakech',
    type: 'lounge',
    city: 'Marrakech',
    address: 'Place Jemaa el-Fna, Medina, 40000 Marrakech',
    capacity: 280,
    description: 'Luxury lounge overlooking the Atlas Mountains, where Italian flair meets Marrakech glamour.',
    openingHours: '20:00 - 04:00',
    coverImage: '/venues/twiga.jpg',
    tables: [
      { id: 't-5-1', number: 1, type: 'vip', capacity: 10, minimumSpend: 8000, shape: 'round', position: { x: 20, y: 10 }, status: 'reserved' },
      { id: 't-5-2', number: 2, type: 'vip', capacity: 8, minimumSpend: 5000, shape: 'rectangle', position: { x: 45, y: 10 }, status: 'available' },
      { id: 't-5-3', number: 3, type: 'standard', capacity: 6, minimumSpend: 2500, shape: 'round', position: { x: 20, y: 35 }, status: 'available' },
      { id: 't-5-4', number: 4, type: 'standard', capacity: 4, minimumSpend: 2000, shape: 'round', position: { x: 45, y: 35 }, status: 'occupied' },
      { id: 't-5-5', number: 5, type: 'bar', capacity: 4, minimumSpend: 1000, shape: 'rectangle', position: { x: 70, y: 50 }, status: 'available' },
    ],
  },
  {
    id: 'venue-6',
    name: 'Le Bar Long',
    type: 'bar',
    city: 'Casablanca',
    address: 'Le Royal Mansour, 37 Avenue Hassan II, Casablanca',
    capacity: 90,
    description: 'Elegantly designed hotel bar serving avant-garde cocktails in an intimate setting.',
    openingHours: '18:00 - 02:00',
    coverImage: '/venues/barlong.jpg',
    tables: [
      { id: 't-6-1', number: 1, type: 'vip', capacity: 6, minimumSpend: 1000, shape: 'round', position: { x: 20, y: 20 }, status: 'available' },
      { id: 't-6-2', number: 2, type: 'standard', capacity: 4, minimumSpend: 400, shape: 'rectangle', position: { x: 45, y: 20 }, status: 'reserved' },
      { id: 't-6-3', number: 3, type: 'bar', capacity: 3, minimumSpend: 200, shape: 'rectangle', position: { x: 70, y: 40 }, status: 'available' },
    ],
  },
]

// ─── PRs / Concierges ──────────────────────────────────────────────────────────

export const prs: PR[] = [
  {
    id: 'pr-1',
    name: 'Youssef Alaoui',
    email: 'youssef.alaoui@nuitblanche.ma',
    phone: '+212 6 12 34 56 78',
    agency: 'Nuit Blanche Agency',
    city: 'Casablanca',
    status: 'active',
    stats: { covers: 52, revenue: 185000, commissionOwed: 18500 },
  },
  {
    id: 'pr-2',
    name: 'Amira Benjelloun',
    email: 'amira@riadnights.ma',
    phone: '+212 6 98 76 54 32',
    agency: 'Riad Nights',
    city: 'Marrakech',
    status: 'active',
    stats: { covers: 42, revenue: 310000, commissionOwed: 31000 },
  },
  {
    id: 'pr-3',
    name: 'Omar Tazi',
    email: 'omar.tazi@casabynuit.com',
    phone: '+212 6 23 45 67 89',
    agency: 'Casa By Nuit',
    city: 'Casablanca',
    status: 'active',
    stats: { covers: 28, revenue: 95000, commissionOwed: 9500 },
  },
  {
    id: 'pr-4',
    name: 'Salma Chraibi',
    email: 'salma@tangerpr.ma',
    phone: '+212 6 34 56 78 90',
    agency: 'Tanger PR',
    city: 'Tanger',
    status: 'active',
    stats: { covers: 22, revenue: 72000, commissionOwed: 7200 },
  },
  {
    id: 'pr-5',
    name: 'Karim Bennani',
    email: 'karim.bennani@gmail.com',
    phone: '+212 6 45 67 89 01',
    city: 'Casablanca',
    status: 'active',
    stats: { covers: 63, revenue: 220000, commissionOwed: 22000 },
  },
  {
    id: 'pr-6',
    name: 'Nadia Berrada',
    email: 'nadia@prestigemarrakech.com',
    phone: '+212 6 12 34 56 00',
    agency: 'Prestige Marrakech',
    city: 'Marrakech',
    status: 'active',
    stats: { covers: 15, revenue: 145000, commissionOwed: 14500 },
  },
  {
    id: 'pr-7',
    name: 'Mehdi Fassi-Fihri',
    email: 'mehdi.fassi@tangerlux.ma',
    phone: '+212 6 56 78 90 12',
    agency: 'Tanger Luxury Concierge',
    city: 'Tanger',
    status: 'pending',
    stats: { covers: 8, revenue: 18000, commissionOwed: 1800 },
  },
  {
    id: 'pr-8',
    name: 'Lina Fassi',
    email: 'lina.fassi@nuitblanche.ma',
    phone: '+212 6 67 89 01 23',
    agency: 'Nuit Blanche Agency',
    city: 'Casablanca',
    status: 'active',
    stats: { covers: 31, revenue: 112000, commissionOwed: 11200 },
  },
  {
    id: 'pr-9',
    name: 'Riad Lahlou',
    email: 'riad@riadnights.ma',
    phone: '+212 6 23 45 67 00',
    agency: 'Riad Nights',
    city: 'Marrakech',
    status: 'inactive',
    stats: { covers: 10, revenue: 48000, commissionOwed: 0 },
  },
  {
    id: 'pr-10',
    name: 'Zineb Lyoubi',
    email: 'zineb.lyoubi@tangerpr.ma',
    phone: '+212 6 78 90 12 34',
    agency: 'Tanger PR',
    city: 'Tanger',
    status: 'pending',
    stats: { covers: 3, revenue: 5400, commissionOwed: 540 },
  },
]

// ─── Reservations ──────────────────────────────────────────────────────────────

export const reservations: Reservation[] = [
  {
    id: 'res-1',
    guestName: 'Hicham El Guerrouj',
    guestPhone: '+212 6 11 22 33 44',
    guestEmail: 'a.beaumont@email.com',
    venueId: 'venue-1',
    eventId: 'event-1',
    prId: 'pr-1',
    type: 'table',
    tablePreference: 'VIP 1',
    partySize: 8,
    status: 'confirmed',
    specialRequests: 'Dom Perignon on arrival',
    date: '2026-04-10',
    minimumSpend: 5000,
  },
  {
    id: 'res-2',
    guestName: 'Isabella Ferretti',
    guestPhone: '+39 345 678 9012',
    guestEmail: 'isabella.f@email.com',
    venueId: 'venue-2',
    eventId: 'event-2',
    prId: 'pr-2',
    type: 'table',
    tablePreference: 'VIP 1',
    partySize: 6,
    status: 'confirmed',
    specialRequests: 'Gluten-free options needed',
    date: '2026-04-11',
    minimumSpend: 10000,
  },
  {
    id: 'res-3',
    guestName: 'Amine Tazi',
    guestPhone: '+212 6 22 33 44 55',
    guestEmail: 'plmarchand@email.com',
    venueId: 'venue-1',
    eventId: 'event-1',
    prId: 'pr-5',
    type: 'guestlist',
    partySize: 4,
    status: 'confirmed',
    date: '2026-04-10',
  },
  {
    id: 'res-4',
    guestName: 'Natasha Volkov',
    guestPhone: '+7 926 123 4567',
    guestEmail: 'natasha.v@email.com',
    venueId: 'venue-3',
    eventId: 'event-3',
    prId: 'pr-4',
    type: 'table',
    tablePreference: 'VIP 1',
    partySize: 10,
    status: 'pending',
    specialRequests: 'Birthday celebration, need cake',
    date: '2026-04-12',
    minimumSpend: 4000,
  },
  {
    id: 'res-5',
    guestName: 'Khalid Bousfiha',
    guestPhone: '+212 6 33 44 55 66',
    guestEmail: 'jb.clement@email.com',
    venueId: 'venue-4',
    prId: 'pr-3',
    type: 'table',
    tablePreference: 'Table 1',
    partySize: 4,
    status: 'confirmed',
    date: '2026-04-08',
    minimumSpend: 500,
  },
  {
    id: 'res-6',
    guestName: 'Elena Papadopoulos',
    guestPhone: '+30 694 567 8901',
    guestEmail: 'elena.p@email.com',
    venueId: 'venue-5',
    prId: 'pr-6',
    type: 'table',
    tablePreference: 'VIP 1',
    partySize: 8,
    status: 'confirmed',
    specialRequests: 'Vegetarian menu preferred',
    date: '2026-04-11',
    minimumSpend: 8000,
  },
  {
    id: 'res-7',
    guestName: 'Samy Benchekroun',
    guestPhone: '+212 6 44 55 66 77',
    guestEmail: 'malefevre@email.com',
    venueId: 'venue-1',
    eventId: 'event-1',
    prId: 'pr-1',
    type: 'guestlist',
    partySize: 6,
    status: 'pending',
    date: '2026-04-10',
  },
  {
    id: 'res-8',
    guestName: 'Yasmine Benali',
    guestPhone: '+212 6 55 66 77 88',
    guestEmail: 'yasmine.b@email.com',
    venueId: 'venue-6',
    prId: 'pr-8',
    type: 'table',
    tablePreference: 'VIP 1',
    partySize: 4,
    status: 'confirmed',
    date: '2026-04-09',
    minimumSpend: 1000,
  },
  {
    id: 'res-9',
    guestName: 'Oliver Hamilton',
    guestPhone: '+44 7700 900123',
    guestEmail: 'oliver.h@email.com',
    venueId: 'venue-2',
    eventId: 'event-2',
    prId: 'pr-2',
    type: 'guestlist',
    partySize: 4,
    status: 'confirmed',
    date: '2026-04-11',
  },
  {
    id: 'res-10',
    guestName: 'Reda Mohammedi',
    guestPhone: '+212 6 66 77 88 99',
    guestEmail: 'f.delacroix@email.com',
    venueId: 'venue-3',
    eventId: 'event-3',
    prId: 'pr-4',
    type: 'guestlist',
    partySize: 2,
    status: 'cancelled',
    date: '2026-04-12',
  },
  {
    id: 'res-11',
    guestName: 'Adriana Costa',
    guestPhone: '+351 912 345 678',
    guestEmail: 'adriana.c@email.com',
    venueId: 'venue-1',
    eventId: 'event-1',
    prId: 'pr-5',
    type: 'table',
    tablePreference: 'Standard 3',
    partySize: 5,
    status: 'confirmed',
    date: '2026-04-10',
    minimumSpend: 1500,
  },
  {
    id: 'res-12',
    guestName: 'Hamza Kettani',
    guestPhone: '+212 6 77 88 99 00',
    guestEmail: 'l.chevallier@email.com',
    venueId: 'venue-5',
    prId: 'pr-6',
    type: 'guestlist',
    partySize: 3,
    status: 'pending',
    date: '2026-04-11',
  },
  {
    id: 'res-13',
    guestName: 'Katarina Johansson',
    guestPhone: '+46 70 123 4567',
    guestEmail: 'katarina.j@email.com',
    venueId: 'venue-2',
    eventId: 'event-2',
    prId: 'pr-2',
    type: 'table',
    tablePreference: 'VIP 2',
    partySize: 6,
    status: 'confirmed',
    specialRequests: 'Champagne tower',
    date: '2026-04-11',
    minimumSpend: 6000,
  },
  {
    id: 'res-14',
    guestName: 'Adil Senhaji',
    guestPhone: '+212 6 88 99 00 11',
    guestEmail: 't.arnaud@email.com',
    venueId: 'venue-4',
    prId: 'pr-3',
    type: 'table',
    tablePreference: 'Table 2',
    partySize: 2,
    status: 'cancelled',
    date: '2026-04-08',
    minimumSpend: 200,
  },
  {
    id: 'res-15',
    guestName: 'Nina Petrova',
    guestPhone: '+7 903 456 7890',
    guestEmail: 'nina.p@email.com',
    venueId: 'venue-1',
    eventId: 'event-4',
    prId: 'pr-8',
    type: 'table',
    tablePreference: 'VIP 2',
    partySize: 8,
    status: 'confirmed',
    specialRequests: 'Cristal on ice at table',
    date: '2026-04-17',
    minimumSpend: 3000,
  },
  {
    id: 'res-16',
    guestName: 'Walid Zniber',
    guestPhone: '+212 6 99 00 11 22',
    guestEmail: 'r.mercier@email.com',
    venueId: 'venue-3',
    eventId: 'event-3',
    prId: 'pr-7',
    type: 'guestlist',
    partySize: 5,
    status: 'confirmed',
    date: '2026-04-12',
  },
  {
    id: 'res-17',
    guestName: 'Fatima-Zahra Benhima',
    guestPhone: '+212 6 10 20 30 40',
    guestEmail: 'charlotte.d@email.com',
    venueId: 'venue-6',
    prId: 'pr-1',
    type: 'table',
    tablePreference: 'Table 2',
    partySize: 3,
    status: 'pending',
    date: '2026-04-09',
    minimumSpend: 400,
  },
  {
    id: 'res-18',
    guestName: 'Viktor Andersen',
    guestPhone: '+45 20 12 34 56',
    guestEmail: 'viktor.a@email.com',
    venueId: 'venue-5',
    prId: 'pr-6',
    type: 'table',
    tablePreference: 'VIP 2',
    partySize: 6,
    status: 'confirmed',
    specialRequests: 'Proposing tonight - discreet champagne delivery',
    date: '2026-04-11',
    minimumSpend: 5000,
  },
  {
    id: 'res-19',
    guestName: 'Leila Hadioui',
    guestPhone: '+212 6 20 30 40 50',
    guestEmail: 'mc.fontaine@email.com',
    venueId: 'venue-1',
    eventId: 'event-4',
    prId: 'pr-5',
    type: 'guestlist',
    partySize: 4,
    status: 'confirmed',
    date: '2026-04-17',
  },
  {
    id: 'res-20',
    guestName: 'Dimitri Stavros',
    guestPhone: '+30 697 234 5678',
    guestEmail: 'd.stavros@email.com',
    venueId: 'venue-2',
    eventId: 'event-5',
    prId: 'pr-2',
    type: 'table',
    tablePreference: 'VIP 1',
    partySize: 10,
    status: 'pending',
    specialRequests: 'Full bottle service, security needed',
    date: '2026-04-18',
    minimumSpend: 10000,
  },
  {
    id: 'res-21',
    guestName: 'Sofia El Amrani',
    guestPhone: '+212 6 30 40 50 60',
    guestEmail: 'a.lambert@email.com',
    venueId: 'venue-4',
    prId: 'pr-3',
    type: 'guestlist',
    partySize: 2,
    status: 'confirmed',
    date: '2026-04-09',
  },
  {
    id: 'res-22',
    guestName: 'Sebastian Muller',
    guestPhone: '+49 170 123 4567',
    guestEmail: 's.muller@email.com',
    venueId: 'venue-3',
    eventId: 'event-6',
    prId: 'pr-4',
    type: 'table',
    tablePreference: 'Standard 2',
    partySize: 4,
    status: 'confirmed',
    date: '2026-04-19',
    minimumSpend: 1500,
  },
  {
    id: 'res-23',
    guestName: 'Ghita Lahlou',
    guestPhone: '+212 6 40 50 60 70',
    guestEmail: 'ines.c@email.com',
    venueId: 'venue-1',
    eventId: 'event-4',
    prId: 'pr-1',
    type: 'table',
    tablePreference: 'Standard 4',
    partySize: 6,
    status: 'pending',
    date: '2026-04-17',
    minimumSpend: 1500,
  },
  {
    id: 'res-24',
    guestName: 'James Whitfield',
    guestPhone: '+44 7911 123456',
    guestEmail: 'j.whitfield@email.com',
    venueId: 'venue-5',
    prId: 'pr-6',
    type: 'guestlist',
    partySize: 2,
    status: 'cancelled',
    date: '2026-04-11',
  },
  {
    id: 'res-25',
    guestName: 'Asmae Boutaleb',
    guestPhone: '+212 6 50 60 70 80',
    guestEmail: 'p.vasseur@email.com',
    venueId: 'venue-6',
    prId: 'pr-8',
    type: 'table',
    tablePreference: 'Bar 3',
    partySize: 2,
    status: 'confirmed',
    date: '2026-04-10',
    minimumSpend: 200,
  },
]

// ─── Events ────────────────────────────────────────────────────────────────────

export const events: Event[] = [
  {
    id: 'event-1',
    venueId: 'venue-1',
    name: 'Nuit Sauvage',
    date: '2026-04-10',
    startTime: '23:00',
    endTime: '06:00',
    genres: ['house', 'techno'],
    guestListCapacity: 200,
    tableReservations: true,
    description: 'A wild night of underground house and techno with DJ Apolline and residents.',
    coverImage: '/events/nuit-sauvage.jpg',
    status: 'open',
  },
  {
    id: 'event-2',
    venueId: 'venue-2',
    name: 'Monaco Grand Prix After-Party',
    date: '2026-04-11',
    startTime: '23:30',
    endTime: '05:00',
    genres: ['hip-hop', 'r&b', 'afrobeats'],
    guestListCapacity: 150,
    tableReservations: true,
    description: 'The official after-party with international DJs celebrating race weekend in style.',
    coverImage: '/events/gp-afterparty.jpg',
    status: 'open',
  },
  {
    id: 'event-3',
    venueId: 'venue-3',
    name: 'Tropical Nights',
    date: '2026-04-12',
    startTime: '21:00',
    endTime: '04:00',
    genres: ['latin', 'reggaeton', 'dancehall'],
    guestListCapacity: 120,
    tableReservations: true,
    description: 'Baoli transforms into a tropical paradise with live percussionists and cocktail specials.',
    coverImage: '/events/tropical-nights.jpg',
    status: 'open',
  },
  {
    id: 'event-4',
    venueId: 'venue-1',
    name: 'Velvet Underground',
    date: '2026-04-17',
    startTime: '23:00',
    endTime: '06:00',
    genres: ['deep house', 'melodic techno'],
    guestListCapacity: 200,
    tableReservations: true,
    description: 'An immersive evening of melodic soundscapes with Berlin-based collective Nachtmusik.',
    coverImage: '/events/velvet-underground.jpg',
    status: 'open',
  },
  {
    id: 'event-5',
    venueId: 'venue-2',
    name: 'Riviera Royale',
    date: '2026-04-18',
    startTime: '23:30',
    endTime: '05:00',
    genres: ['commercial', 'pop', 'dance'],
    guestListCapacity: 150,
    tableReservations: true,
    description: 'Jimmy\'z signature Saturday soiree featuring resident DJ Marco and special guests.',
    coverImage: '/events/riviera-royale.jpg',
    status: 'open',
  },
  {
    id: 'event-6',
    venueId: 'venue-3',
    name: 'Cote d\'Azur Sunset Sessions',
    date: '2026-04-19',
    startTime: '18:00',
    endTime: '01:00',
    genres: ['chill house', 'nu-disco', 'balearic'],
    guestListCapacity: 100,
    tableReservations: true,
    description: 'Golden hour vibes on the terrace with sundowners, live sax, and sunset DJ sets.',
    coverImage: '/events/sunset-sessions.jpg',
    status: 'open',
  },
]

// ─── Guests ────────────────────────────────────────────────────────────────────

export const guests: Guest[] = [
  {
    id: 'guest-1',
    name: 'Hicham El Guerrouj',
    phone: '+212 6 11 22 33 44',
    email: 'a.beaumont@email.com',
    isVip: true,
    tags: ['high-spender', 'regular', 'influencer'],
    notes: [
      { id: 'n-1', content: 'Prefers Dom Perignon, always requests Table 1 at L\'Arc.', author: 'Youssef Alaoui', date: '2026-03-15' },
      { id: 'n-2', content: 'Brought 3 new clients last visit. Great network.', author: 'Karim Bennani', date: '2026-02-20' },
    ],
    stats: { totalVisits: 28, totalSpend: 142000, avgSpend: 5071, avgPartySize: 7, firstVisit: '2024-06-15' },
  },
  {
    id: 'guest-2',
    name: 'Isabella Ferretti',
    phone: '+39 345 678 9012',
    email: 'isabella.f@email.com',
    isVip: true,
    tags: ['high-spender', 'celebrity'],
    notes: [
      { id: 'n-3', content: 'Italian fashion designer. Needs privacy and discreet service.', author: 'Amira Benjelloun', date: '2026-03-01' },
    ],
    stats: { totalVisits: 12, totalSpend: 195000, avgSpend: 16250, avgPartySize: 6, firstVisit: '2025-01-10' },
  },
  {
    id: 'guest-3',
    name: 'Amine Tazi',
    phone: '+212 6 22 33 44 55',
    email: 'plmarchand@email.com',
    isVip: false,
    tags: ['regular'],
    notes: [],
    stats: { totalVisits: 15, totalSpend: 8500, avgSpend: 567, avgPartySize: 4, firstVisit: '2025-03-20' },
  },
  {
    id: 'guest-4',
    name: 'Natasha Volkov',
    phone: '+7 926 123 4567',
    email: 'natasha.v@email.com',
    isVip: true,
    tags: ['high-spender', 'birthday-upcoming'],
    notes: [
      { id: 'n-4', content: 'Birthday on April 12. Wants a surprise cake and sparklers.', author: 'Salma Chraibi', date: '2026-03-28' },
    ],
    stats: { totalVisits: 8, totalSpend: 64000, avgSpend: 8000, avgPartySize: 9, firstVisit: '2025-07-14' },
  },
  {
    id: 'guest-5',
    name: 'Khalid Bousfiha',
    phone: '+212 6 33 44 55 66',
    email: 'jb.clement@email.com',
    isVip: false,
    tags: ['foodie', 'regular'],
    notes: [
      { id: 'n-5', content: 'Wine connoisseur. Prefers Burgundy and natural wines.', author: 'Omar Tazi', date: '2026-01-12' },
    ],
    stats: { totalVisits: 22, totalSpend: 11000, avgSpend: 500, avgPartySize: 3, firstVisit: '2024-09-05' },
  },
  {
    id: 'guest-6',
    name: 'Elena Papadopoulos',
    phone: '+30 694 567 8901',
    email: 'elena.p@email.com',
    isVip: true,
    tags: ['high-spender', 'yacht-owner'],
    notes: [
      { id: 'n-6', content: 'Greek shipping heiress. Frequents Marrakech venues during summer.', author: 'Nadia Berrada', date: '2026-02-10' },
    ],
    stats: { totalVisits: 6, totalSpend: 88000, avgSpend: 14667, avgPartySize: 8, firstVisit: '2025-06-20' },
  },
  {
    id: 'guest-7',
    name: 'Samy Benchekroun',
    phone: '+212 6 44 55 66 77',
    email: 'malefevre@email.com',
    isVip: false,
    tags: ['new'],
    notes: [],
    stats: { totalVisits: 2, totalSpend: 1200, avgSpend: 600, avgPartySize: 5, firstVisit: '2026-03-01' },
  },
  {
    id: 'guest-8',
    name: 'Yasmine Benali',
    phone: '+212 6 55 66 77 88',
    email: 'yasmine.b@email.com',
    isVip: true,
    tags: ['regular', 'influencer'],
    notes: [
      { id: 'n-7', content: '200k followers on Instagram. Always posts stories from the venue.', author: 'Lina Fassi', date: '2026-03-18' },
    ],
    stats: { totalVisits: 18, totalSpend: 32000, avgSpend: 1778, avgPartySize: 4, firstVisit: '2025-02-14' },
  },
  {
    id: 'guest-9',
    name: 'Oliver Hamilton',
    phone: '+44 7700 900123',
    email: 'oliver.h@email.com',
    isVip: false,
    tags: ['international', 'regular'],
    notes: [
      { id: 'n-8', content: 'London banker, visits Marrakech monthly. Low-key but consistent spender.', author: 'Amira Benjelloun', date: '2026-01-25' },
    ],
    stats: { totalVisits: 10, totalSpend: 24000, avgSpend: 2400, avgPartySize: 4, firstVisit: '2025-04-18' },
  },
  {
    id: 'guest-10',
    name: 'Nina Petrova',
    phone: '+7 903 456 7890',
    email: 'nina.p@email.com',
    isVip: true,
    tags: ['high-spender', 'model'],
    notes: [
      { id: 'n-9', content: 'Top model, always requests Cristal. Arrives late, stays until close.', author: 'Lina Fassi', date: '2026-03-05' },
    ],
    stats: { totalVisits: 14, totalSpend: 78000, avgSpend: 5571, avgPartySize: 6, firstVisit: '2025-01-20' },
  },
  {
    id: 'guest-11',
    name: 'Fatima-Zahra Benhima',
    phone: '+212 6 10 20 30 40',
    email: 'charlotte.d@email.com',
    isVip: false,
    tags: ['regular', 'cocktail-lover'],
    notes: [],
    stats: { totalVisits: 9, totalSpend: 4500, avgSpend: 500, avgPartySize: 3, firstVisit: '2025-08-10' },
  },
  {
    id: 'guest-12',
    name: 'Dimitri Stavros',
    phone: '+30 697 234 5678',
    email: 'd.stavros@email.com',
    isVip: true,
    tags: ['high-spender', 'yacht-owner', 'international'],
    notes: [
      { id: 'n-10', content: 'Close friend of Elena Papadopoulos. Always books the best table.', author: 'Amira Benjelloun', date: '2026-02-28' },
      { id: 'n-11', content: 'Requires security detail - coordinate with his team in advance.', author: 'Nadia Berrada', date: '2026-03-10' },
    ],
    stats: { totalVisits: 5, totalSpend: 125000, avgSpend: 25000, avgPartySize: 10, firstVisit: '2025-07-01' },
  },
  {
    id: 'guest-13',
    name: 'Sofia El Amrani',
    phone: '+212 6 30 40 50 60',
    email: 'a.lambert@email.com',
    isVip: false,
    tags: ['regular'],
    notes: [
      { id: 'n-12', content: 'Journalist for Vogue Arabia. Treat with discretion.', author: 'Omar Tazi', date: '2026-01-30' },
    ],
    stats: { totalVisits: 7, totalSpend: 3200, avgSpend: 457, avgPartySize: 2, firstVisit: '2025-09-15' },
  },
  {
    id: 'guest-14',
    name: 'Katarina Johansson',
    phone: '+46 70 123 4567',
    email: 'katarina.j@email.com',
    isVip: true,
    tags: ['high-spender', 'international'],
    notes: [
      { id: 'n-13', content: 'Swedish tech entrepreneur. Loves champagne towers and grand gestures.', author: 'Amira Benjelloun', date: '2026-03-22' },
    ],
    stats: { totalVisits: 4, totalSpend: 52000, avgSpend: 13000, avgPartySize: 6, firstVisit: '2025-11-01' },
  },
  {
    id: 'guest-15',
    name: 'Asmae Boutaleb',
    phone: '+212 6 50 60 70 80',
    email: 'p.vasseur@email.com',
    isVip: false,
    tags: ['new', 'cocktail-lover'],
    notes: [],
    stats: { totalVisits: 3, totalSpend: 900, avgSpend: 300, avgPartySize: 2, firstVisit: '2026-02-01' },
  },
]

// ─── Conversations ─────────────────────────────────────────────────────────────

export const conversations: Conversation[] = [
  {
    id: 'conv-1',
    name: 'Youssef Alaoui',
    initials: 'YA',
    lastMessage: 'Table 1 is confirmed for El Guerrouj tonight. Dom P on ice.',
    timestamp: '2026-04-06T14:32:00',
    unread: true,
    role: 'PR',
    venue: 'L\'Arc Casablanca',
  },
  {
    id: 'conv-2',
    name: 'Amira Benjelloun',
    initials: 'AB',
    lastMessage: 'Dimitri Stavros wants VIP 1 for Saturday. Can we hold it?',
    timestamp: '2026-04-06T12:15:00',
    unread: true,
    role: 'PR',
    venue: 'Jimmy\'z Marrakech',
  },
  {
    id: 'conv-3',
    name: 'Salma Chraibi',
    initials: 'SC',
    lastMessage: 'Natasha\'s birthday cake is sorted. Sparklers at midnight.',
    timestamp: '2026-04-05T22:45:00',
    unread: false,
    role: 'PR',
    venue: 'Baoli Tanger',
  },
  {
    id: 'conv-4',
    name: 'Karim Bennani',
    initials: 'KB',
    lastMessage: 'I have 3 tables worth of clients for Nuit Sauvage. Sending details now.',
    timestamp: '2026-04-05T18:20:00',
    unread: false,
    role: 'PR',
    venue: 'L\'Arc Casablanca',
  },
  {
    id: 'conv-5',
    name: 'Nadia Berrada',
    initials: 'NB',
    lastMessage: 'Elena confirmed for Friday at Twiga. She wants the terrace VIP.',
    timestamp: '2026-04-05T16:00:00',
    unread: false,
    role: 'PR',
    venue: 'Twiga Marrakech',
  },
]

// ─── Messages (for conversation detail views) ──────────────────────────────────

export const messages: Record<string, Message[]> = {
  'conv-1': [
    { id: 'msg-1-1', senderId: 'pr-1', content: 'Salut! El Guerrouj wants his usual Table 1 for Friday. Party of 8.', timestamp: '2026-04-06T10:00:00', isOwn: false },
    { id: 'msg-1-2', senderId: 'self', content: 'Table 1 is available. 5000 minimum as usual. Confirmed?', timestamp: '2026-04-06T10:15:00', isOwn: true },
    { id: 'msg-1-3', senderId: 'pr-1', content: 'Confirmed. He also wants Dom Perignon ready on arrival.', timestamp: '2026-04-06T10:22:00', isOwn: false },
    { id: 'msg-1-4', senderId: 'self', content: 'Done. Anything else for Nuit Sauvage? Guest list is filling up.', timestamp: '2026-04-06T11:00:00', isOwn: true },
    { id: 'msg-1-5', senderId: 'pr-1', content: 'Samy Benchekroun wants guestlist for 6. Still pending his confirmation.', timestamp: '2026-04-06T13:45:00', isOwn: false },
    { id: 'msg-1-6', senderId: 'self', content: 'Noted. Let me know once he confirms. We have about 40 spots left.', timestamp: '2026-04-06T14:00:00', isOwn: true },
    { id: 'msg-1-7', senderId: 'pr-1', content: 'Table 1 is confirmed for El Guerrouj tonight. Dom P on ice.', timestamp: '2026-04-06T14:32:00', isOwn: false },
  ],
  'conv-2': [
    { id: 'msg-2-1', senderId: 'pr-2', content: 'Bonjour! Stavros is arriving Saturday with a group of 10. He wants the best table.', timestamp: '2026-04-06T09:30:00', isOwn: false },
    { id: 'msg-2-2', senderId: 'self', content: 'VIP 1 is the best we have. 10K minimum. He knows the drill?', timestamp: '2026-04-06T09:45:00', isOwn: true },
    { id: 'msg-2-3', senderId: 'pr-2', content: 'Of course. He also needs his security detail accommodated.', timestamp: '2026-04-06T10:00:00', isOwn: false },
    { id: 'msg-2-4', senderId: 'self', content: 'We can arrange that. Have his team contact our head of security directly.', timestamp: '2026-04-06T10:30:00', isOwn: true },
    { id: 'msg-2-5', senderId: 'pr-2', content: 'Dimitri Stavros wants VIP 1 for Saturday. Can we hold it?', timestamp: '2026-04-06T12:15:00', isOwn: false },
  ],
  'conv-3': [
    { id: 'msg-3-1', senderId: 'pr-4', content: 'Quick update on the Natasha Volkov birthday reservation.', timestamp: '2026-04-05T20:00:00', isOwn: false },
    { id: 'msg-3-2', senderId: 'self', content: 'Go ahead, what do we need?', timestamp: '2026-04-05T20:10:00', isOwn: true },
    { id: 'msg-3-3', senderId: 'pr-4', content: 'She wants a 3-tier cake, sparklers, and the DJ to play her favourite song at midnight.', timestamp: '2026-04-05T20:30:00', isOwn: false },
    { id: 'msg-3-4', senderId: 'self', content: 'What song?', timestamp: '2026-04-05T20:35:00', isOwn: true },
    { id: 'msg-3-5', senderId: 'pr-4', content: 'She wants "La Vie en Rose" - the Grace Jones version. I\'ll send the Spotify link.', timestamp: '2026-04-05T21:00:00', isOwn: false },
    { id: 'msg-3-6', senderId: 'self', content: 'Perfect. DJ is briefed. Cake?', timestamp: '2026-04-05T22:00:00', isOwn: true },
    { id: 'msg-3-7', senderId: 'pr-4', content: 'Natasha\'s birthday cake is sorted. Sparklers at midnight.', timestamp: '2026-04-05T22:45:00', isOwn: false },
  ],
  'conv-4': [
    { id: 'msg-4-1', senderId: 'pr-5', content: 'I have a big group for Nuit Sauvage. 3 tables possibly.', timestamp: '2026-04-05T16:00:00', isOwn: false },
    { id: 'msg-4-2', senderId: 'self', content: 'Nice. What are we looking at?', timestamp: '2026-04-05T16:15:00', isOwn: true },
    { id: 'msg-4-3', senderId: 'pr-5', content: 'Adriana Costa - Standard table for 5. Plus two guestlist groups.', timestamp: '2026-04-05T16:30:00', isOwn: false },
    { id: 'msg-4-4', senderId: 'self', content: 'Standard 3 is free. 1500 minimum. Guest list names?', timestamp: '2026-04-05T17:00:00', isOwn: true },
    { id: 'msg-4-5', senderId: 'pr-5', content: 'I have 3 tables worth of clients for Nuit Sauvage. Sending details now.', timestamp: '2026-04-05T18:20:00', isOwn: false },
  ],
  'conv-5': [
    { id: 'msg-5-1', senderId: 'pr-6', content: 'Elena Papadopoulos is coming Friday to Twiga with her usual group.', timestamp: '2026-04-05T14:00:00', isOwn: false },
    { id: 'msg-5-2', senderId: 'self', content: 'VIP 1 terrace? She always wants that one.', timestamp: '2026-04-05T14:15:00', isOwn: true },
    { id: 'msg-5-3', senderId: 'pr-6', content: 'Exactly. Party of 8, vegetarian menu. 8K minimum is fine.', timestamp: '2026-04-05T14:30:00', isOwn: false },
    { id: 'msg-5-4', senderId: 'self', content: 'Booked. Also Viktor Andersen is at VIP 2 same night - the proposal. Keep it discreet.', timestamp: '2026-04-05T15:00:00', isOwn: true },
    { id: 'msg-5-5', senderId: 'pr-6', content: 'Elena confirmed for Friday at Twiga. She wants the terrace VIP.', timestamp: '2026-04-05T16:00:00', isOwn: false },
  ],
}

// ─── Dashboard Summary Stats ───────────────────────────────────────────────────

export const dashboardStats = {
  totalRevenue: 1_285_400,
  totalReservations: 847,
  totalGuests: 2_340,
  activePRs: 8,
  avgSpendPerTable: 4_280,
  guestListConversion: 72,
  revenueChange: 12.5,
  reservationChange: 8.3,
  guestChange: 15.2,
  prChange: -2.1,
}
